import { NpcDef } from 'src/features/npcs/types/npc-def.interface';
import { NpcKind } from 'src/features/npcs/types/npc-kind.type';

export const NPCS: Record<NpcKind, NpcDef> = {
    boar: {
        kind: 'boar',
        wild: true,
        name: 'Boar',
        hp: 90,
        speed: 120,
        radius: 14,
        damage: 12,
        attackRange: 30,
        attackCooldown: 1.2,
        hostile: false,
        color: '#966e50',
        dark: '#573d27',
        loot: { meat_raw: [3, 5], leather: [8, 14], bone: [4, 8], animal_fat: [4, 9] },
    },
    wolf: {
        kind: 'wolf',
        wild: true,
        name: 'Wolf',
        hp: 80,
        speed: 155,
        radius: 13,
        damage: 22,
        attackRange: 28,
        attackCooldown: 0.9,
        hostile: true,
        color: '#8e97a5',
        dark: '#505d6d',
        loot: { meat_raw: [2, 4], leather: [6, 12], bone: [3, 6], animal_fat: [2, 5] },
    },
    bear: {
        kind: 'bear',
        wild: true,
        name: 'Bear',
        hp: 340,
        speed: 92,
        radius: 22,
        damage: 42,
        attackRange: 40,
        attackCooldown: 1.3,
        hostile: true,
        color: '#88522c',
        dark: '#523119',
        loot: { meat_raw: [8, 14], leather: [20, 34], bone: [10, 18], animal_fat: [14, 28] },
    },
    scientist: {
        kind: 'scientist',
        name: 'Scientist',
        hp: 130,
        speed: 118,
        radius: 12,
        damage: 14,
        attackRange: 30,
        attackCooldown: 1.0,
        hostile: true,
        color: '#e6ebf0',
        dark: '#758494',
        gun: { damage: 19, range: 470, cooldown: 1.15, speed: 900, spread: 0.07 },
        loot: { scrap: [8, 20], pistol_ammo: [4, 12], metal: [10, 30], medkit: [0, 1] },
    },
};
