import { ClanSkillDef } from 'src/features/clans/types/clan-skill-def.interface';
import { ClanSkill } from 'src/features/clans/types/clan-skill.type';

export const CLAN_SKILLS: Record<ClanSkill, ClanSkillDef> = {
    amateur: {
        // Three cells minimum: a compound has to fit a cupboard, a box, a furnace,
        // a fire and a bed without them fighting over the same square.
        skill: 'amateur',
        label: 'amateur',
        weight: 4,
        baseSize: 3,
        tier: 'wood',
        members: 2,
        techPerDay: 0.5,
        raidPace: 0.6,
        wealth: 0.5,
        buildStep: 9,
    },
    seasoned: {
        skill: 'seasoned',
        label: 'seasoned',
        weight: 3,
        baseSize: 3,
        tier: 'stone',
        members: 4,
        techPerDay: 1,
        raidPace: 1,
        wealth: 1,
        buildStep: 7,
    },
    veteran: {
        skill: 'veteran',
        label: 'veteran',
        weight: 2,
        baseSize: 4,
        tier: 'stone',
        members: 6,
        techPerDay: 1.6,
        raidPace: 1.35,
        wealth: 1.8,
        buildStep: 5.5,
    },
    expert: {
        skill: 'expert',
        label: 'expert',
        weight: 1,
        baseSize: 4,
        tier: 'metal',
        members: 8,
        techPerDay: 2.4,
        raidPace: 1.7,
        wealth: 3,
        buildStep: 4,
    },
};
